spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:flyway;
    username: sa
    password:
  h2:
    console:
      enabled: true
  flyway:
    baseline-version: 1
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
  jpa:
    show-sql: true

